### ISSUE TITLE
Fetch data from Backend to Frontend

### ISSUE THREAD

**Issue by ayush-git228** [ayush-git228/WebStore#2]
Not being able to fetch data from node backend to react(redux) and react hooks frontend.

**Comment by rachleona** [comment]
Hi! I might be able to help if you would just give me more details about the problem

**Comment by ayush-git228** [comment]
> 
> 
> Hi! I might be able to help if you would just give me more details about the problem

Hi @rachleona, so the problem is that nothing is being displayed on the home screen and product screen as the Redux state is stuck in request(loading) state(as saw in redux dev tools), as you know there are three states(request,  success, fail). So you can see if you can bring the state from request to success state, i.e. display items from the backend on the front-end side.

**Comment by rachleona** [comment]
So I took quick look, stuff is kinda messy, your frontend has **91 vulnerabilities** according to npm, zero comments about what should happen and it seems like you pretty much ignored most of the warnings npm and your console gave you. This probably isn't your first react project but just some simple screening and I was able to catch quite a bit of syntax mistakes in your backend, so it's probably better that you start cleaning your code up a bit first (comments are important so that your teammates or even future you can understand the code when working with a large codebase), it'll help you pinpoint the problems. Correcting those minor mistakes should at least get your request to respond if not run successfully. I'll continue investigating the problems with the listProducts route for you but please read up a bit on higher order functions like filter(), find() and map() in js to help you write your code more efficiently (and easier to read).

**Comment by ayush-git228** [comment]
Hi @rachleona, thanks for the valuable feedback, I am trying to make the code look less messy so it would be easy to read for you . Also regarding errors, the React tools, and npm tools not showing errors on my system so whether there is typos or some other errors (in the backend), pl let me know and also I have worked on the backend regarding this errors checking if it is ok and I'm assuming the problem must be lying with the frontend. So if you can look into it. Thanks

**Comment by rachleona** [comment]
Go back to the basics, just look at the js console. Here's your fatal error:
<img width="268" alt="Screenshot 2020-10-17 at 7 10 50 PM" src="https://user-images.githubusercontent.com/34417799/96350745-0d191180-10af-11eb-8a12-5f3f57aa999b.png">
Go read up on cors and you'll understand better of why it wasn't working. Check out what I changed and hopefully it'll help you fix the rest of your app.

I completely understand the ambitiousness of a learning dev, I myself is still learning, and it's a good to be ambitious, but do remember your basics. Debug after each small implementation, read the javascript console and just console.log() to debug. Also don't ignore the warnings in js console, they're there to help you.
<img width="601" alt="Screenshot 2020-10-17 at 7 45 14 PM" src="https://user-images.githubusercontent.com/34417799/96351147-5ff3c880-10b1-11eb-9671-939ab56b63db.png">

Lastly, good job and keep up the good work!

**Comment by ayush-git228** [comment]
Thankyou @rachleona for correcting the messed up code and I would do correct the mistakes and lack of knowledge about cors. The backend was so bad. I was more inclined on correcting frontend when there was so much to do at the backend. And yes I will make my debugging process more efficient.

**Comment by ayush-git228** [comment]
Dev and debug should go hand in hand rather than doing it at once, so thanks for the learning. And there is still a lot of things that I need to correct on this project so going forward for that.
